config/routes.rb
require "sidekiq/web"
require "sidekiq-scheduler/web"

Rails.application.routes.draw do
  resource :my_page, only: [:show] do
    get :confirm 
    # patch :withdraw
    delete :withdraw
  end
 
  namespace :admin do
    root "dashboard#index"
    resources :users, only: [:index]
    resources :notification_managements, only: [:index]
  end

  devise_for :admins,
    controllers: {
      sessions: "admin/sessions",
      registrations: "admin/registrations"
    }

  
  get "how_to/show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # lineログインの準備ができたらONに、
  # devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  authenticated :user do
    root to: "home_pages#index", as: :user_root
  end

  # ログイン前のルートページ
  unauthenticated do
    root to: "top_pages#top"
  end

  # LINE ログインの準備ができたらOFFに
  # devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}


  devise_for :users, controllers: {
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    delete "logout", to: "devise/sessions#destroy", as: :logout
  end

  Rails.logger.info "===== ROUTES FILE LOADED ====="

  resources :anniversaries, only: %i[index show new create edit update destroy] do
    collection do
      get :calendar
    end
  end
  # has_oneなのでresorce
  resource :partner
  resources :gift_suggestions, only: %i[ index new create destroy]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  if Rails.env.development?
    post "/dev_login", to: "dev_sessions#create"
    delete "/dev_logout", to: "dev_sessions#destroy"
  end

  if Rails.env.development?
    # viewでいるのはindexのみ
    resources :notification_managements, only: %i[  new create edit update destroy ]
  end

  if Rails.env.development?
  Sidekiq::Web.use(Rack::Auth::Basic) do |user_id, password|
    [ user_id, password ] == [ ENV["USER_ID"], ENV["USER_PASSWORD"] ]
  end
  mount Sidekiq::Web, at: "/sidekiq"
  end
end

app/views/shared/_admin_header.html.erb
<header class="navbar sticky-top bg-dark flex-md-nowrap p-0 shadow data-bs-theme="dark">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 p-3 fs-6 text-white fw-bold" href="#">Bootstrap 5 dashboard</a>
    
    <form  class="d-flex mx-4 d-none d-md-flex" role="search">
        <input type="search" placeholder="search" aria-label="search">
        <button class="btn" type="submit ">search</button>
    </form>
    <ul class="navbar-nav flex-row d-md-none">
        <li class="nav-item text-nowrap">
            <button class="nav-link px-3 text-white" type="button" data-bs-toggle="offcanvas" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
                <i class="bi bi-list"></i>
            </button>
        </li>
    </ul>
    </header>
    
    

app/views/shared/_admin_sidebar.html.erb
        <div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-teritary shadow">
            <div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu" aria-labelledby="sidebarMenuLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title fw-semibold" id="sidebarMenuLabel">bootstrap 5 dashboard</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu" aria-label="Close"></button>
                </div>

                <div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center fw-semibold gap-2" aria-current="page"  href="#">
                                <i class="bi bi-house-ffill"></i>
                                <%= link_to "Dashbard", admin_root_path%>
                            </a>
                        </li>
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center  gap-2">
                                <%= link_to "users",admin_users_path %>
                            </a>
                        </li>
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center gap-2"  href="#">
                                <i class="bi bi-people"></i>
                                <%= link_to "notificaiton_managements", admin_notification_managements_path %>
                            </a>
                        </li>
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center gap-2" aria-current="page"  href="#">
                                <i class="bi bi-graph-up"></i>
                                Dashboard4
                            </a>
                        </li>
                    </ul>

                    <hr class="my-3">

                    <ul class="nav flex-column mb-auto">
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center gap-2" href="#">
                                <i class="bi bi-gear-wide-connected"></i>
                                setings
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center gap-2" href="#">
                                <i class="bi bi-door-closed"></i>
                                sign <output></output>
                            </a>
                        </li>
                    </ul>

                </div>
            </div>
        </div>

app/views/shared/_before_login_header.html.erb
<nav class="navbar bg-body-tertiary sticky-top">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">トップ</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
                <%= link_to "利用規約","#", {class: "nav-link active"}%>
            </li>
            <li class="nav-item">
                <%= link_to "使い方","#", {class: "nav-link active"}%>
            </li>
            <li class="nav-item">
                <%= link_to "お問い合わせ","#", {class: "nav-link active"}%>
            </li>
            <li class="nav-item">
                <%= link_to "プライバシーポリシー","#", {class: "nav-link active"}%>
            </li>
          </ul>
        </div>
      </div>
      <% if Rails.env.development? %>
          <%= button_to "Devログイン", "/dev_login" %>
      <% end %>
      <div class="ms-auto d-flex gap-2">
            <%= button_to "ログイン", user_line_omniauth_authorize_path,method: :post, form: { data: {turbo: false}} %>
        </div>    
      </div>
    </div>
  </nav>
  

app/views/shared/_confirm_delete_modal.html.erb
  <div data-controller="modal">
    <%= link_to "削除", "#", class: "btn btn-danger", data: { action: "click->modal#open"} %>

    <div data-modal-target="modal" class="modal">
        <div class="modal-content">
          <p>大切な人の情報をなくしてもいいですか？</p>
          <div class="modal-buttons">
            <%= link_to "はい", partner_path, data: { turbo_method: :delete }, class: "btn btn-danger" %>
            <button type="button" data-action="click->modal#close" class= "btn btn-secondary">いいえ</button>
        </div>
      </div>

    </div>
  </div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |type, message| %>
<div>
    <%= message %>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container">
<footer class="mt-auto d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
       <span class="mb-6 mb-md-0 ext-body-secondary">© 2025 for_mine</span>
    </div>
    <ul class="nav col-md--4 justify-content-end list-unstyled d-flex">
        <li class="ms-3">
            <%= link_to "利用規約","#", {class: "navbar-brand"}%>
        </li>
    <ul class="nav col-md--4 justify-content-end list-unstyled d-flex">
        <li class="ms-3">
            <%= link_to "お問い合わせ","#", {class: "navbar-brand"}%>
        </li>
    <ul class="nav col-md--4 justify-content-end list-unstyled d-flex">
        <li class="ms-3">
            <%= link_to "プライベートポリシー","#", {class: "navbar-brand"}%>
        </li>
    </ul>
</footer>    
</div>

app/views/shared/_header.html.erb
<nav class="navbar bg-body-tertiary sticky-top">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">トップ</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
                <%= link_to "利用規約","#", {class: "nav-link active"}%>
            </li>
            <li class="nav-item">
                <%= link_to "使い方", how_to_show_path, {class: "nav-link active"}%>
            </li>
            <li class="nav-item">
                <%= link_to "お問い合わせ","#", {class: "nav-link active"}%>
            </li>
            <li class="nav-item">
                <%= link_to "プライバシーポリシー","#", {class: "nav-link active"}%>
            </li>
          </ul>
        </div>
      </div>
      <div>
        <%= link_to "ホーム", user_root_path, class: "navbar-brand"%>
        <!-- link_to は基本「最後に options を1つ」なので、data: と class: を 同じハッシュにまとめる必要があります。 -->
        <%= link_to "ログアウト",
        logout_path,
        class: "navbar-brand",
        data: { turbo_method: :delete } %>
        <%= link_to "マイページ", my_page_path, class: "navbar-brand" %>
      </div>
    </div>
  </nav>
  