config/routes.rb
require "sidekiq/web"
require "sidekiq-scheduler/web"

Rails.application.routes.draw do
  resource :my_page, only: [:show] do
    get :confirm 
    # patch :withdraw
    delete :withdraw
  end
 
  namespace :admin do
    root "dashboard#index"
    resources :users, only: [:index]
    resources :notification_managements, only: [:index]
  end

  devise_for :admins,
    controllers: {
      sessions: "admin/sessions",
      registrations: "admin/registrations"
    }

  
  get "how_to/show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # lineログインの準備ができたらONに、
  # devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  authenticated :user do
    root to: "home_pages#index", as: :user_root
  end

  # ログイン前のルートページ
  unauthenticated do
    root to: "top_pages#top"
  end

  # LINE ログインの準備ができたらOFFに
  # devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}


  devise_for :users, controllers: {
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    delete "logout", to: "devise/sessions#destroy", as: :logout
  end

  Rails.logger.info "===== ROUTES FILE LOADED ====="

  resources :anniversaries, only: %i[index show new create edit update destroy] do
    collection do
      get :calendar
    end
  end
  # has_oneなのでresorce
  resource :partner
  resources :gift_suggestions, only: %i[ index new create destroy]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  if Rails.env.development?
    post "/dev_login", to: "dev_sessions#create"
    delete "/dev_logout", to: "dev_sessions#destroy"
  end

  if Rails.env.development?
    # viewでいるのはindexのみ
    resources :notification_managements, only: %i[  new create edit update destroy ]
  end

  if Rails.env.development?
  Sidekiq::Web.use(Rack::Auth::Basic) do |user_id, password|
    [ user_id, password ] == [ ENV["USER_ID"], ENV["USER_PASSWORD"] ]
  end
  mount Sidekiq::Web, at: "/sidekiq"
  end
end

app/models/anniversary.rb
# == Schema Information
#
# Table name: anniversaries
#
#  id               :bigint           not null, primary key
#  anniversary_date :date             not null
#  title            :string           not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  user_id          :bigint           not null
#
# Indexes
#
#  index_anniversaries_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Anniversary < ApplicationRecord
    include Hashid::Rails

    belongs_to :user
    has_one :notification_setting, dependent: :destroy


    validates :title, presence:  { message: "を入力してね" }
    validates :anniversary_date, presence:  { message: "を入力してね" }

    scope :notification_target_get, ->(date) { where(notification_on: true).where(anniversary_date: date) }


    scope :notification_enabled, -> { joins(:notification_setting).where(notification_settings: { is_enabled: true }) }
    #  scope :notification_enables , ->{ joins(:notification_setting).where('notification_settings.is_enabled = ?','true')}
    #  scope :notification_target_in_range, -> { joins(:notification_setting).where('notification_settings.start_on <= ?', Date.current).where('anniversary.anniversary_date >= ?', Date.current) }
    #  scope :notification_target_in_range, -> { joins(:notification_setting).where(notification_settings: {start_on: ..Date.current}) }



    def anniversary_calculate
      # ゴーr 記念日からどれくらいったか
      today = Date.current
     diff =  (anniversary_date - today).to_i
     if diff == 0
        "今日が記念日"
     else diff < 0
        "記念日から#{diff.abs}日経ちました"
       # 今日より後ならダメ　何にも出ないよ
     end
    end

    def next_anniversary
      today = Date.current
      year = today.year
      mon = anniversary_date.month
      da = anniversary_date.day

      if mon == 2 && da == 29 && !Date.leap?(year)
        this_year = Date.new(year, 2, 28)
      else
        this_year =  Date.new(year, mon, da)
      end

      if this_year < today
        year += 1
        if mon == 2 && da == 29 && !Date.leap?(year)
           this_year = Date.new(year, 2, 28)
        else
          this_year = Date.new(year, mon, da)
        end
      end
        this_year
    end


    def start_time
      # next_anniversary
      anniversary_date
    end

    def self.ransackable_attributes(auth_object = nil)
      [ "anniversary_date", "title" ]
    end
    def self.ransackable_associations(auth_object = nil)
      [ "notification_setting", "user" ]
    end
end

app/controllers/anniversaries_controller.rb
class AnniversariesController < ApplicationController
    before_action :authenticate_user!

    def index
        # @anniversaries = current_user.anniversaries
        # 記念日もカレンダーででるようにしてもいいかも
        @q = current_user.anniversaries.ransack(params[:q])
        @anniversaries = @q.result.includes(:notification_setting)

        set_meta_tags(
          title: "記念日一覧"
        )
    end

    def calendar
      @anniversaries = current_user.anniversaries
    end

    def show
        @anniversary = current_user.anniversaries.find_by_hashid(params[:id])
    end


    def new
        @anniversary = current_user.anniversaries.build
        @form = AnniversaryNotificationSettingForm.new(anniversary: @anniversary)
      end

    def create
        @anniversary = current_user.anniversaries.build
        @form = AnniversaryNotificationSettingForm.new(
          # user: current_user,
          anniversary: @anniversary,
          **anniversary_notification_setting_params
        )
        if @form.save
          redirect_to anniversaries_path, notice: "記念日を登録しました"
        else
          render :new, status: :unprocessable_entity
        end
    end


    def edit
        @anniversary = current_user.anniversaries.find_by_hashid(params[:id])
        @form = AnniversaryNotificationSettingForm.new(
            # user: current_user,
            anniversary: @anniversary
          )
    end

    def update
        @anniversary = current_user.anniversaries.find_by_hashid(params[:id])
        Rails.logger.debug params[:anniversary_notification_setting_form].inspect
        @form = AnniversaryNotificationSettingForm.new(
            # user: current_user,
            anniversary: @anniversary,
            **anniversary_notification_setting_params
          )
        if @form.save
            redirect_to anniversaries_path, success: "記念日を更新しました"
        else
            flash.now[:danger] = "記念日更新に失敗しました"
            render :edit, status: :unprocessable_content
        end
    end
    def destroy
        anniversary = current_user.anniversaries.find_by_hashid(params[:id])
        anniversary.destroy!
        redirect_to anniversaries_path, success: "記念日を削除しました"
    end



    private


    def anniversary_notification_setting_params
        params.require(:anniversary_notification_setting_form).permit(:title, :anniversary_date, :is_enabled, :frequency_days,
        :notification_time, :start_on)
    end
end

app/helpers/anniversaries_helper.rb
module AnniversariesHelper
end

app/views/anniversaries/_form.html.erb
<% form_with_options = form.anniversary.persisted? ?
  { url: anniversary_path(form.anniversary), method: :patch } :
  { url: anniversaries_path, method: :post} %>
<%= form_with model: form ,**form_with_options do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <div class="mb-3">
    <%= f.label :title, "タイトル" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <div class="row">
      <div class="col">
     <%= f.label :anniversary_date, "記念日" %>
    <%= f.date_field :anniversary_date, class: "form-control" %>         
      </div>
      <div class="col">
        <div class="row">
          <div>
            <p>通知設定</p>
          </div>
          <div class="col">
            <%= f.radio_button :is_enabled, true, checked: @form.is_enabled %>
            <%= f.label :is_enabled, "ON" %>
          </div>
          <div class="col">
            <%= f.radio_button :is_enabled, false, checked: !@form.is_enabled %>
            <%= f.label :is_enabled, "OFF" %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div>
    <%= f.select :frequency_days, options_for_select(NotificationSetting.frequency_days.map {|k,v| [k,v]}, f.object.frequency_days) %>
  </div>
 
  <div>
    <%= f.select :notification_time,
    options_for_select((0..23).map { |h| ["%02d:00" % h, "%02d:00" % h] }, f.object.notification_time&.strftime("%H:00")),
    { include_blank: true }%>
  </div>
  <div>
    <%= f.date_field :start_on %>
  </div>

  <%= f.submit submit_label, class: "btn btn-primary" %>
<% end %>  

app/views/anniversaries/_search.html.erb
<%= search_form_for q ,url: anniversaries_path, method: :get do |f| %>
<%= f.label :title_cont, "タイトル" %>
<%= f.search_field :title_cont %>
<%= f.label :anniversary_date_during_month, "期間"%>
<%= raw sprintf(
    f.date_select(
      :anniversary_date_during_month,
      discard_day: true,
      include_blank: true,
      use_month_numbers: true,
      date_separator: '%s'),
    '年 ') + '月' %>
<div class="actions ransack-submit"><%= f.submit "検索" %></div>
<%= link_to "リセット", anniversaries_path %>
<% end %>

app/views/anniversaries/calendar.html.erb
<h1>記念日</h1>
<%= month_calendar events: @anniversaries do |date,anniversaries| %>
<%= date.day %>

<% anniversaries.each do |anniversary| %>
  <div>
    <%= link_to anniversary.title, anniversary_path(anniversary) %>
  </div>
<% end %>

<% end %>

<%= link_to "back_to_index",anniversaries_path %>

app/views/anniversaries/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1>記念日編集</h1>

      <%= render "form", form: @form, submit_label: "更新" %>

      <div class="mt-4">
        <%= link_to "一覧へ", anniversaries_path %>
      </div>
    </div>
  </div>
</div>

app/views/anniversaries/index.html.erb
<%= render "search", q:@q %>


<h1>記念日一覧</h1>
<div class="container py-3">
    <% if @anniversaries.present? %>
      <div class="row g-3">
        <% @anniversaries.each do |anniversary| %>
          <div class="col-12 col-md-6 col-lg-4">
            <div class="card h-100 shadow-sm">
              <div class="card-body">
                <h5 class="card-title mb-2">
                    タイトル：  <%= anniversary.title %>
                </h5> 
                <p class="card-text mb-2">
                  記念日：<%= anniversary.anniversary_date %>
                </p>
                <p class="card-text mb-2">
                  通知日：<%= anniversary.notification_setting&.start_on %>
                </p>
                <p class="card-text mb-0">
                  通知設定：<%= anniversary.notification_setting.is_enabled ? "ON" : "OFF" %>
                </p>
                <div class="text-success mt-2"><%= anniversary.anniversary_calculate %></div>
              </div>
  
              <div class="card-body pt-0">
                <%= link_to "詳細", anniversary_path(anniversary), class: "card-link" %>
                <%= link_to "編集", edit_anniversary_path(anniversary), class: "card-link" %>
                <%= link_to "削除", anniversary_path(anniversary),
                      data: { turbo_method: :delete},
                      class: "card-link text-danger" %>
              </div>
            </div>
          </div>
        <% end %>
        
        <%= link_to "記念日追加", new_anniversary_path, class: "btn-primary" %>
        <div class="mt-5">
          <p>通知を受け取るには公式ライン登録が必要です(まだ未実装)</p>
          <a href="https://lin.ee/XNdU8tj"><img src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png" alt="友だち追加" height="36" border="0"></a>          
        </div>

      </div>
      <a href="<%= ENV['APP_BASE_URL'] %>" class="href">aaa</a>


    <% else %>
      <p>記念日がありません</p>

    <div class="mt-3 ms-3">
      <%= link_to "記念日作成", new_anniversary_path, class: "btn-primary " %>
    </div>

    <div class="mt-5">
      <p>通知を受け取るには公式ライン登録が必要です(まだ未実装)</p>
      <a href="https://lin.ee/XNdU8tj"><img src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png" alt="友だち追加" height="36" border="0"></a>          
    </div>

  <% end %>
  </div>
  
  <%= link_to "go to calendar",calendar_anniversaries_path %>
  
  
  <!-- <p class="card-text mb-0">
    通知設定： anniversary.notification_settings.notifiation_on ? "ON" : "OFF" %>
  </p> -->

app/views/anniversaries/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1>記念日作成</h1>

      <%= render "form", form: @form, submit_label: "作成" %>

      <div class="mt-4">
        <%= link_to "一覧へ", anniversaries_path %>
      </div>
    </div>
  </div>
</div>

app/views/anniversaries/show.html.erb
<div class="container pt-5">
    <div class="row mb-3">
      <div class="col-lg-8 offset-lg-2">
        <h1><%= "記念日詳細" %></h1>
  
        <article class="card">
          <div class="card-body">
            <div class="row">
              <div class="col-md-6">
                <h3>タイトル: <%= @anniversary.title %></h3>
              </div>
              <div class="col-md-6">
                <h3>日: <%= @anniversary.anniversary_date %></h3>
              </div>
            </div>
            <div>
              <%= link_to "編集", edit_anniversary_path(@anniversary) %>
              <%= link_to "削除", anniversary_path(@anniversary), data: { turbo_method: :delete } %>
            </div>
          </div>
        </article>
      </div>
    </div>
    <div>
      <%= link_to "一覧へ", anniversaries_path %>
    </div>
</div>